### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-node#72]
Users started to get "socket hang up" error. This is what I know:
NodeJS: 20

Error:
```
,"name":"Error","message":"socket hang up","stack":"Error: socket hang up\n at Client.handleError (/app/node_modules/.pnpm/convertapi@1.11.1/node_modules/convertapi/lib/client.js:127:11)\n at /app/node_modules/.pnpm/convertapi@1.11.1/node_modules/convertapi/lib/client.js:62:96"
```

Code:
```
do {
try {
return await this.api.convert(toFormat, params, fromFormat, conversionTimeout);
} catch (e: any) {
lastError = e;
tries += 1;
}
} while (tries < this.maxRetries);
```

Conversion: docx to pdf

Params:
```
{
"File": "<local filelsystem>/output.docx"
}
```

File: [output.docx](https://github.com/ConvertAPI/convertapi-node/files/13424918/output.docx)

**Comment by JonasJasas** [comment]
User was using old version.
